# Generated by Django 4.2.20 on 2025-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("haemoglobin", models.FloatField()),
                ("wbc", models.FloatField()),
                ("differential", models.FloatField()),
                ("rbc", models.FloatField()),
                ("platelet", models.FloatField()),
                ("pdw", models.FloatField()),
            ],
        ),
    ]
